# Generated by Django 3.1.1 on 2020-12-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0002_auto_20201222_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_type',
            field=models.CharField(default=1, max_length=22),
            preserve_default=False,
        ),
    ]
