# Generated by Django 3.1.1 on 2020-12-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0003_products_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='cname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='msmapp.categories'),
            preserve_default=False,
        ),
    ]
