# Generated by Django 3.1.1 on 2021-01-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0006_auto_20210105_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
