# Generated by Django 3.1.1 on 2021-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0007_auto_20210118_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
