# Generated by Django 3.1.1 on 2021-01-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0009_auto_20210118_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
