# Generated by Django 3.0.11 on 2021-02-04 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0011_auto_20210119_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmapp.Register'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('added_time1', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmapp.Register')),
            ],
        ),
    ]
