# Generated by Django 3.0.11 on 2021-03-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msmapp', '0014_auto_20210226_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmapp.Register'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmapp.Register'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmapp.Register'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipt', models.CharField(max_length=33)),
                ('product_names', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=200)),
                ('product_qun', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmapp.Register')),
            ],
        ),
    ]
